#include "nova/lexer.hpp"
#include <cctype>
#include <unordered_map>
#include <stdexcept>
namespace nova{
Lexer::Lexer(std::string s):source(std::move(s)){}
void Lexer::advance(){if(pos<source.size()){if(source[pos]=='\n'){++line;column=1;}else ++column;++pos;}}
char Lexer::peek()const{return pos<source.size()?source[pos]:'\0';}
char Lexer::peek_next()const{return pos+1<source.size()?source[pos+1]:'\0';}
std::vector<Token> Lexer::scan(){std::vector<Token>o;while(pos<source.size()){char c=peek();if(c==' '||c=='\t'||c=='\r'){advance();continue;}int l=line,col=column;if(c=='\n'){o.push_back({TokenType::Newline,"\\n",l,col});advance();continue;}if(c=='#'){while(peek()!='\n'&&peek()!='\0')advance();continue;}if(std::isdigit((unsigned char)c)){std::string s;while(std::isdigit((unsigned char)peek())||peek()=='.'){s+=peek();advance();}o.push_back({TokenType::Number,s,l,col});continue;}if(std::isalpha((unsigned char)c)||c=='_'){std::string s;while(std::isalnum((unsigned char)peek())||peek()=='_'){s+=peek();advance();}static std::unordered_map<std::string,TokenType>k={{"let",TokenType::Let},{"const",TokenType::Const},{"fn",TokenType::Fn},{"if",TokenType::If},{"else",TokenType::Else},{"while",TokenType::While},{"for",TokenType::For},{"in",TokenType::In},{"return",TokenType::Return},{"break",TokenType::Break},{"continue",TokenType::Continue},{"class",TokenType::Class},{"this",TokenType::This},{"try",TokenType::Try},{"catch",TokenType::Catch},{"finally",TokenType::Finally},{"throw",TokenType::Throw},{"import",TokenType::Import},{"true",TokenType::True},{"false",TokenType::False},{"null",TokenType::Null}};auto it=k.find(s);o.push_back({it==k.end()?TokenType::Identifier:it->second,s,l,col});continue;}if(c=='"'){advance();std::string s;while(peek()!='"'&&peek()!='\0'){if(peek()=='\\'){advance();char e=peek();s+=e=='n'?'\n':e=='t'?'\t':e;advance();}else{s+=peek();advance();}}if(peek()=='"')advance();else throw std::runtime_error("Unterminated string");o.push_back({TokenType::String,s,l,col});continue;}auto one=[&](TokenType t){o.push_back({t,std::string(1,c),l,col});advance();};if(c=='+')one(TokenType::Plus);else if(c=='-')one(TokenType::Minus);else if(c=='*')one(TokenType::Star);else if(c=='/')one(TokenType::Slash);else if(c=='%')one(TokenType::Percent);else if(c=='(')one(TokenType::LeftParen);else if(c==')')one(TokenType::RightParen);else if(c=='{')one(TokenType::LeftBrace);else if(c=='}')one(TokenType::RightBrace);else if(c=='[')one(TokenType::LeftBracket);else if(c==']')one(TokenType::RightBracket);else if(c==',')one(TokenType::Comma);else if(c=='.')one(TokenType::Dot);else if(c==':')one(TokenType::Colon);else if(c=='='&&peek_next()=='='){advance();advance();o.push_back({TokenType::EqualEqual,"==",l,col});}else if(c=='!'&&peek_next()=='='){advance();advance();o.push_back({TokenType::BangEqual,"!=",l,col});}else if(c=='<'&&peek_next()=='='){advance();advance();o.push_back({TokenType::LessEqual,"<=",l,col});}else if(c=='>'&&peek_next()=='='){advance();advance();o.push_back({TokenType::GreaterEqual,">=",l,col});}else if(c=='=')one(TokenType::Equal);else if(c=='!')one(TokenType::Bang);else if(c=='<')one(TokenType::Less);else if(c=='>')one(TokenType::Greater);else throw std::runtime_error("Unexpected character: "+std::string(1,c));}o.push_back({TokenType::End,"",line,column});return o;}
std::string token_name(TokenType t){return std::to_string((int)t);}
}
